#!/usr/bin/env bash
# Copyright 2026 Michele Moser
# SPDX-License-Identifier: Apache-2.0
set -u
. /usr/local/libexec/wasalight-i18n
clear
echo "BITFOCUS COMPANION UPDATE"
_ "Updates are allowed only in MAINTENANCE mode."
echo
_ "Authorize the operation in the graphical window using the chamsys password."
echo
echo
pkexec /usr/local/sbin/wasalight-companion-update
rc=$?
echo
if ((rc == 0)); then
    _ "Companion update completed."
    echo
elif ((rc == 126)); then
    _ "Authentication cancelled: Companion was not modified."
    echo
else
    printf "$(_ 'Companion update failed (exit code %s).')\n" "$rc"
fi
_ "Press Enter to close."
echo
read -r _
exit "$rc"
