include /etc/wasalight/logrotate.d

/data/log/wasalight-magicq-console.log /data/log/wasalight-magicq-session.log /data/log/wasalight-control.log /data/log/wasalight-network-tools.log /data/log/wasalight-xorg-startup.log {
    size 5M
    rotate 5
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0640 chamsys chamsys
    su chamsys chamsys
}

/data/log/wasalight-health.log {
    size 2M
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0640 chamsys chamsys
    su chamsys chamsys
}

/data/log/wasalight-update.log {
    size 5M
    rotate 5
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0640 root adm
    su root adm
}
